### ISSUE TITLE
Broken media query

### ISSUE THREAD

**Issue by chrismwilliams** [chrismwilliams/astro-cube-boilerplate-tailwind-V4alpha#2]
tailwindcss@4.0.0-alpha.7 doesn't support the use of the screen() function, so this: 

```css
@media screen(md) {
 .grid[data-layout="lg:10/2"] {
   grid-template-columns: clamp(40rem, 80vw, 60rem);
 }
}

@media screen(lg) {
 .grid[data-layout="lg:10/2"] {
   grid-template-columns: 10fr 2fr;
 }
}
```

in `src/css/components/grid.css` breaks dev/build.
